apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepull-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepull-demo
  template:
    metadata:
      labels:
        app: imagepull-demo
    spec:
      containers:
      - name: app
        image: this-image-definitely-does-not-exist:v1