apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pending-demo
  template:
    metadata:
      labels:
        app: pending-demo
    spec:
      nodeSelector:
        node-type: impossible-node
      containers:
      - name: app
        image: nginx