apiVersion: v1
kind: Service
metadata:
  name: kubernetes-copilot
  namespace: kubernetes-copilot
  labels:
    app.kubernetes.io/name: kubernetes-copilot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubernetes-copilot
  ports:
    - name: http
      port: 80
      targetPort: http
