from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class RemediationCandidate:
    """A deterministic remediation option generated by local policy."""

    candidate_id: str
    action_type: str
    risk_level: str
    action_category: str
    description: str
    rationale: str
    target_kind: str
    target_name: str
    namespace: str
    solves_root_cause: bool
    executable: bool
    parameters: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class RemediationAction:
    """A validated remediation action recommended by the LLM."""

    candidate_id: str
    action_type: str
    risk_level: str
    action_category: str
    description: str
    rationale: str
    target_kind: str
    target_name: str
    namespace: str
    solves_root_cause: bool
    parameters: dict[str, str] = field(default_factory=dict)
    executable: bool = False
    policy_reason: str = ""


@dataclass(frozen=True, slots=True)
class RemediationPlan:
    """Structured remediation recommendations parsed from an LLM response."""

    actions: list[RemediationAction]
    parse_error: str = ""


@dataclass(frozen=True, slots=True)
class RemediationExecutionResult:
    """Result of an attempted remediation action."""

    success: bool
    message: str
